repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-json
    - id: pretty-format-json
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-symlinks
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: trailing-whitespace
    - id: end-of-file-fixer
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.3
    hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tfsec
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md
        - --hook-config=--add-to-existing-file=true
